export const MADHYA_PRADESH_DISTRICTS = [
  "Agar Malwa", "Alirajpur", "Anuppur", "Ashoknagar", "Balaghat", "Barwani", "Betul", 
  "Bhind", "Bhopal", "Burhanpur", "Chhatarpur", "Chhindwara", "Damoh", "Datia", 
  "Dewas", "Dhar", "Dindori", "Guna", "Gwalior", "Harda", "Indore", "Jabalpur", 
  "Jhabua", "Katni", "Khandwa", "Khargone", "Maihar", "Mandla", "Mandsaur", 
  "Mauganj", "Morena", "Narmadapuram", "Narsinghpur", "Neemuch", "Niwari", 
  "Pandhurna", "Panna", "Raisen", "Rajgarh", "Ratlam", "Rewa", "Sagar", "Satna", 
  "Sehore", "Seoni", "Shahdol", "Shajapur", "Sheopur", "Shivpuri", "Sidhi", 
  "Singrauli", "Tikamgarh", "Ujjain", "Umaria", "Vidisha"
];

export const TRANSLATIONS = {
  en: {
    dashboard: "Dashboard",
    patientIntake: "Patient Intake",
    registrationForm: "Registration Form",
    fullName: "Full Name",
    age: "Age",
    contact: "Contact Number",
    reason: "Reason for Visit",
    district: "District",
    selectDistrict: "Select District",
    confirmRegistration: "Confirm Registration",
    waitConsultation: "Waiting for Consultation",
    clinicalReview: "Clinical Review",
    mealDistribution: "Meal Distribution",
    deliveredTray: "Photo of Delivered Tray",
    status: "Status",
    timeAdded: "Time Added",
    actions: "Actions",
    viewDetails: "View Details",
    medicalAdvice: "Medical Advice",
    completeReview: "Complete & Send to Meal",
    confirmDelivery: "Confirm Delivery",
    systemOversight: "System Oversight",
    patientData: "Patient Data Log"
  },
  hi: {
    dashboard: "डैशबोर्ड",
    patientIntake: "मरीज पंजीकरण",
    registrationForm: "पंजीकरण फॉर्म",
    fullName: "पूरा नाम",
    age: "आयु",
    contact: "संपर्क नंबर",
    reason: "आने का कारण",
    district: "जिला",
    selectDistrict: "जिला चुनें",
    confirmRegistration: "पंजीकरण की पुष्टि करें",
    waitConsultation: "परामर्श की प्रतीक्षा",
    clinicalReview: "नैदानिक समीक्षा",
    mealDistribution: "भोजन वितरण",
    deliveredTray: "वितरित भोजन की फोटो",
    status: "स्थिति",
    timeAdded: "शामिल करने का समय",
    actions: "कार्रवाई",
    viewDetails: "विवरण देखें",
    medicalAdvice: "चिकित्सा सलाह",
    completeReview: "समीक्षा पूरी करें और भोजन के लिए भेजें",
    confirmDelivery: "वितरण की पुष्टि करें",
    systemOversight: "सिस्टम निरीक्षण",
    patientData: "मरीज डेटा लॉग",
    gender: "लिंग",
    address: "पता",
    block: "ब्लॉक",
    village: "गाँव",
    abhaId: "ABHA आईडी / आधार",
    sickleCellStatus: "सिकल सेल स्थिति",
    medicalHistory: "चिकित्सा इतिहास",
    presentSymptoms: "वर्तमान लक्षण",
    currentMedication: "वर्तमान दवाएं",
    dietLifestyle: "आहार और जीवन शैली",
    counsellingTopics: "परामर्श के विषय",
    nutritionKit: "पोषण किट वितरण",
    referral: "रेफरल",
    feedback: "प्रतिक्रिया और समझ",
    counsellorDetails: "परामर्शदाता विवरण"
  }
};
