export const MADHYA_PRADESH_DISTRICTS = [
  "Agar Malwa", "Alirajpur", "Anuppur", "Ashoknagar", "Balaghat", "Barwani", "Betul", 
  "Bhind", "Bhopal", "Burhanpur", "Chhatarpur", "Chhindwara", "Damoh", "Datia", 
  "Dewas", "Dhar", "Dindori", "Guna", "Gwalior", "Harda", "Indore", "Jabalpur", 
  "Jhabua", "Katni", "Khandwa", "Khargone", "Maihar", "Mandla", "Mandsaur", 
  "Mauganj", "Morena", "Narmadapuram", "Narsinghpur", "Neemuch", "Niwari", 
  "Pandhurna", "Panna", "Raisen", "Rajgarh", "Ratlam", "Rewa", "Sagar", "Satna", 
  "Sehore", "Seoni", "Shahdol", "Shajapur", "Sheopur", "Shivpuri", "Sidhi", 
  "Singrauli", "Tikamgarh", "Ujjain", "Umaria", "Vidisha"
];

export const TRANSLATIONS = {
  en: {
    dashboard: "Dashboard",
    patientIntake: "Patient Intake",
    registrationForm: "Registration Form",
    fullName: "Full Name",
    age: "Age",
    contact: "Contact Number",
    reason: "Reason for Visit",
    district: "District",
    selectDistrict: "Select District",
    confirmRegistration: "Confirm Registration",
    waitConsultation: "Waiting for Consultation",
    clinicalReview: "Clinical Review",
    mealDistribution: "Meal Distribution",
    deliveredTray: "Photo of Delivered Tray",
    status: "Status",
    timeAdded: "Time Added",
    actions: "Actions",
    viewDetails: "View Details",
    medicalAdvice: "Medical Advice",
    completeReview: "Complete & Send to Meal",
    confirmDelivery: "Confirm Delivery",
    systemOversight: "System Oversight",
    patientData: "Patient Data Log",
    gender: "Gender",
    address: "Address",
    block: "Block",
    village: "Village",
    abhaId: "ABHA ID / Aadhar",
    sickleCellStatus: "Sickle Cell Status",
    medicalHistory: "Medical History",
    presentSymptoms: "Present Symptoms",
    currentMedication: "Current Medication",
    dietLifestyle: "Diet & Lifestyle",
    counsellingTopics: "Counselling Topics",
    nutritionKit: "Nutrition Kit Distribution",
    referral: "Referral",
    feedback: "Feedback & Understanding",
    counsellorDetails: "Counsellor Details",
    basicInfo: "Basic Information",
    locationDetails: "Location Details",
    submit: "Submit",
    cancel: "Cancel",
    errorTitle: "Something went wrong",
    errorSubtitle: "The application encountered an unexpected error. Our team has been notified.",
    retryButton: "Try Again",
    reloadButton: "Reload Application",
    copyDiagnostics: "Copy Debug Info",
    showTechnical: "Show Technical Details",
    diagnosticsCopied: "Diagnostics copied to clipboard",
    settings: "Settings",
    myDistricts: "My Districts",
    assignDistricts: "Assign Districts",
    onlyDataFromThese: "Only data from these districts will be visible to you.",
    role: "Role",
    liveAnalytics: "Live Analytics",
    syncPaused: "Sync Paused",
    patientHistory: "Comprehensive history of all patient interactions.",
    waitMeal: "Waiting for Meal",
    patientsWaitMeal: "Patients awaiting nutritional support.",
    fullAdminAudit: "Full Administrative Record Audit",
    clinicalReviewDetail: "Comprehensive Clinical Review",
    mealDeliveryAudit: "Meal Delivery & Safety Audit",
    returningPatient: "Returning Patient",
    historicalDataLoaded: "Historical data loaded.",
    backToDirectory: "Back to Directory",
    viewRegistrations: "View Registrations",
    newRegistration: "New Patient Registration",
    returningPatientFound: "Returning patient found!",
    goodMorning: "Good Morning",
    goodAfternoon: "Good Afternoon",
    goodEvening: "Good Evening",
    totalPatients: "Total Patients",
    activeQueue: "Active Queue",
    completed: "Completed",
    efficiency: "Efficiency",
    todayNew: "Today's New",
    pendingConsult: "Pending Consult",
    queueSize: "Queue Size",
    todayReviews: "Today's Reviews",
    pendingMeals: "Pending Meals",
    todayServed: "Today's Served",
    searchPatient: "Search patient...",
    noMealsPending: "No meals pending distribution.",
    years: "years",
    male: "Male",
    female: "Female",
    yes: "Yes",
    no: "No",
    summary: "Summary",
    details: "Details",
    action: "Action",
    finalConsultNotes: "Final Consultation Notes",
    enterAdvice: "Enter advice...",
    attachReports: "Attach Reports",
    uploadReport: "Upload Report",
    capturePhoto: "Capture Photo",
    patientPhotograph: "Patient Photograph",
    registrar: "Registrar",
    consultant: "Consultant",
    mealServer: "Meal Server",
    clinicalEvaluationWait: "Patients awaiting clinical evaluation.",
    recentRegistrations: "Manage and track recently registered patients.",
    observerDashboard: "System Observer Dashboard",
    readOnlyAccess: "Read-only access to real-time patient metrics.",
    realtimeProgress: "View real-time progress across districts.",
    updateSuccess: "Record updated successfully",
    updateFailed: "Failed to update record",
    reviewQueued: "Review queued!",
    deliveryQueued: "Delivery queued!",
    registrationQueued: "Registration queued!",
    notes: "Notes",
    enterNotes: "Enter delivery notes...",
    needsCorrection: "Needs Correction",
    escalated: "Escalated",
    returnToRegistrar: "Return to Registrar",
    escalate: "Escalate",
    patientDirectory: "Patient Directory",
    patientRecord: "Patient Record",
    updateDetails: "Update Details"
  },
  hi: {
    dashboard: "डैशबोर्ड",
    patientIntake: "मरीज पंजीकरण",
    registrationForm: "पंजीकरण फॉर्म",
    fullName: "पूरा नाम",
    age: "आयु",
    contact: "संपर्क नंबर",
    reason: "आने का कारण",
    district: "जिला",
    selectDistrict: "जिला चुनें",
    confirmRegistration: "पंजीकरण की पुष्टि करें",
    waitConsultation: "परामर्श की प्रतीक्षा",
    clinicalReview: "नैदानिक समीक्षा",
    mealDistribution: "भोजन वितरण",
    deliveredTray: "वितरित भोजन की फोटो",
    status: "स्थिति",
    timeAdded: "शामिल करने का समय",
    actions: "कार्रवाई",
    viewDetails: "विवरण देखें",
    medicalAdvice: "चिकित्सा सलाह",
    completeReview: "समीक्षा पूरी करें और भोजन के लिए भेजें",
    confirmDelivery: "वितरण की पुष्टि करें",
    systemOversight: "प्रणाली निरीक्षण",
    patientData: "मरीज डेटा लॉग",
    gender: "लिंग",
    address: "पता",
    block: "ब्लॉक",
    village: "गाँव",
    abhaId: "ABHA आईडी / आधार",
    sickleCellStatus: "सिकल सेल स्थिति",
    medicalHistory: "चिकित्सा इतिहास",
    presentSymptoms: "वर्तमान लक्षण",
    currentMedication: "वर्तमान दवाएं",
    dietLifestyle: "आहार और जीवन शैली",
    counsellingTopics: "परामर्श के विषय",
    nutritionKit: "पोषण किट वितरण",
    referral: "रेफरल",
    feedback: "प्रतिक्रिया और समझ",
    counsellorDetails: "परामर्शदाता विवरण",
    basicInfo: "बुनियादी जानकारी",
    locationDetails: "स्थान विवरण",
    submit: "सबमिट करें",
    cancel: "रद्द करें",
    errorTitle: "कुछ गलत हो गया",
    errorSubtitle: "एप्लिकेशन में एक अप्रत्याशित त्रुटि आई है। हमारी टीम को सूचित कर दिया गया है।",
    retryButton: "पुनः प्रयास करें",
    reloadButton: "एप्लिकेशन रीलोड करें",
    copyDiagnostics: "डीबग जानकारी कॉपी करें",
    showTechnical: "तकनीकी विवरण दिखाएं",
    diagnosticsCopied: "डायग्नोस्टिक्स क्लिपबोर्ड पर कॉपी किया गया",
    settings: "सेटिंग्स",
    myDistricts: "मेरे जिले",
    assignDistricts: "जिले सौंपें",
    onlyDataFromThese: "केवल इन जिलों का डेटा आपको दिखाई देगा।",
    role: "भूमिका",
    liveAnalytics: "लाइव एनालिटिक्स",
    syncPaused: "सिंक रुका हुआ",
    patientHistory: "सभी मरीज बातचीत का व्यापक इतिहास।",
    waitMeal: "भोजन की प्रतीक्षा",
    patientsWaitMeal: "पोषण सहायता की प्रतीक्षा कर रहे मरीज।",
    fullAdminAudit: "पूर्ण प्रशासनिक रिकॉर्ड ऑडिट",
    clinicalReviewDetail: "व्यापक नैदानिक समीक्षा",
    mealDeliveryAudit: "भोजन वितरण और सुरक्षा ऑडिट",
    returningPatient: "पुराना मरीज",
    historicalDataLoaded: "पिछला डेटा लोड किया गया।",
    backToDirectory: "निर्देशिका पर वापस जाएं",
    viewRegistrations: "पंजीकरण देखें",
    newRegistration: "नया मरीज पंजीकरण",
    returningPatientFound: "पुराना मरीज मिला!",
    goodMorning: "शुभ प्रभात",
    goodAfternoon: "शुभ दोपहर",
    goodEvening: "शुभ संध्या",
    totalPatients: "कुल मरीज",
    activeQueue: "सक्रिय कतार",
    completed: "पूरा हुआ",
    efficiency: "दक्षता",
    todayNew: "आज के नए",
    pendingConsult: "परामर्श लंबित",
    queueSize: "कतार का आकार",
    todayReviews: "आज की समीक्षाएं",
    pendingMeals: "लंबित भोजन",
    todayServed: "आज परोसा गया",
    searchPatient: "मरीज खोजें...",
    noMealsPending: "कोई भोजन वितरण लंबित नहीं है।",
    years: "साल",
    male: "पुरुष",
    female: "महिला",
    yes: "हाँ",
    no: "नहीं",
    summary: "सारांश",
    details: "विवरण",
    action: "कार्रवाई",
    finalConsultNotes: "अंतिम परामर्श नोट्स",
    enterAdvice: "सलाह दर्ज करें...",
    attachReports: "रिपोर्ट संलग्न करें",
    uploadReport: "रिपोर्ट अपलोड करें",
    capturePhoto: "फोटो लें",
    patientPhotograph: "मरीज की फोटो",
    registrar: "पंजीकार",
    consultant: "परामर्शदाता",
    mealServer: "भोजन वितरक",
    clinicalEvaluationWait: "नैदानिक मूल्यांकन की प्रतीक्षा कर रहे मरीज।",
    recentRegistrations: "हाल ही में पंजीकृत मरीजों का प्रबंधन करें।",
    observerDashboard: "सिस्टम ऑब्जर्वर डैशबोर्ड",
    readOnlyAccess: "रीअल-टाइम मरीज मेट्रिक्स तक केवल पढ़ने की पहुंच।",
    realtimeProgress: "जिलों में रीअल-टाइम प्रगति देखें।",
    updateSuccess: "रिकॉर्ड सफलतापूर्वक अपडेट किया गया",
    updateFailed: "रिकॉर्ड अपडेट करने में विफल",
    reviewQueued: "समीक्षा कतार में!",
    deliveryQueued: "वितरण कतार में!",
    registrationQueued: "पंजीकरण कतार में!",
    notes: "टिप्पणियाँ",
    enterNotes: "वितरण नोट्स दर्ज करें...",
    needsCorrection: "सुधार आवश्यक",
    escalated: "एस्केलेटेड",
    returnToRegistrar: "रजिस्ट्रार को वापस करें",
    escalate: "एस्केलेट करें",
    patientDirectory: "मरीज निर्देशिका",
    patientRecord: "मरीज रिकॉर्ड",
    updateDetails: "विवरण अपडेट करें"
  }
};
